language: ruby
rvm:
  - 2.1.2

env:
  global:
    - secure: "jpjjwqMa9J2yVFkSplxQB9cRKh6JRN1gWash8p+qAkubjVayLUKbokVwqlqjkbIfDw+e8giAN+AcuBdb8CNibfDLWfV0NgJeZPxZ4/Gryq1iTpYJMGr53GqUGbtNQNSKb83kMJYPXSRLgGkTD82OdTmQh5CyMI2UN9+btJcyLvY="
    - secure: "scIz0DAivmyfkl7GHOmIQ+V5Qwrh0d9pxhklEJ+q4ha92oHO49fLXP1NHsKoctDlYNaxnhGIMBYXxO6U324H6hgRbGhSl/LkhtGA+6IkfUleefhvWAGODlGIv1mla5VSfvveldZyTthw8MC/wqyawyJi79G8YrqZPtL4eQfZZTI="
    - secure: "cirQFKEF/YuWW9qP7/6iAaglilJhxkve4fPb8y5qet4mkRv2HyoVLZ72VcdyG0UWp+ITRD4w2jzzReUdWOvY2EpBmjIf5rrfsYp/kwWPUP/4LPtqqG1l+KE8aQVnpU1dBOSCK1gB5a0JMTkbvcMkgtdDaVPAC5dSfI5SpN/zpiw="
    - SAUCY: true
  matrix:
    - DB: postgresql

addons:
  code_climate:
    repo_token:
      secure: "bcVuNU/YGdm+E0Anw0xTeUdFb9qFay1ifpyGZRNBN3GT2TByAb9U/kLJUWCgJx4dm5melJZxZ7Mm2D3uTJJ17DpHBtB1r3AIgEQ6xqX7iAeIczytv1du+9U7O38dLYzLcBEu4m3WUPjWCDXCqi5fP0+t4Ry0ShZlcV+jhAgl2Zo="
  sauce_connect: true

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace

before_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then wget -qO- https://toolbelt.heroku.com/install.sh | sh; export PATH=$PATH:/usr/local/heroku/bin; heroku pgbackups:transfer codekwondo::DATABASE_URL codekwondo-staging::DATABASE_URL -a codekwondo-staging --confirm codekwondo-staging; fi

deploy:
  provider: heroku
  api_key:
    secure: "ZxPs+jSM9Y+yAFxY8WNs/C93QL7+0ygJJ3NJLJQ4L2GCnPiDkSHD4nazlSUeTnk3glVy98niNnusD0mYMP/r5WHWP4xmJzfoEKpA3YZvyld9SLaFJ+ibiXCepQrk9ByV83OULcYbZWUWs90tZD3GyvluNjDR4+uSFeanKYuHMFg="
  app:
    master: codekwondo-staging
    production: codekwondo
  on:
    repo: chrisvfritz/codekwondo
  run: "bundle exec rake db:migrate"

bundler_args: --without development production

script:
  - bundle exec rspec